#ifndef SAMPLE_6_H
#define SAMPLE_6_H

#include"neotest/neotest.h"

#ifdef TEST_SAMPLE_6

NEOTEST_STATIC_CHECK_VALUE_EQ(100,100.00);
NEOTEST_STATIC_CHECK_VALUE_EQ(100,200.00);

NEOTEST_STATIC_CHECK_TYPE_SAME(int,int);
NEOTEST_STATIC_CHECK_TYPE_SAME(int,double);

NEOTEST_STATIC_CHECK_TYPE_SAME(
    NEOTEST_MAKE_STATIC_STRING("Hello")
    ,NEOTEST_MAKE_STATIC_STRING("Hello")
);

NEOTEST_STATIC_CHECK_TYPE_SAME(
    NEOTEST_MAKE_STATIC_STRING("Hello")
    ,NEOTEST_MAKE_STATIC_STRING("World!")
);

#endif

#endif//SAMPLE_6_H
